# Joshua C. Fjelstul, Ph.D.
# ungadm R Package

#' Authenticate with the UNGA-DM Database API
#'
#' @description This function allows you to authenticate with the UNGA-DM
#'   Database API. It creates a session. You need to provide your username and
#'   password to authenticate. This function returns an object of class
#'   \code{ungadm_session} that contains the credentials necessary to request
#'   password-protected data from the UNGA-DM Database API. You need to pass
#'   this session object into any function that requires a \code{session}
#'   argument. If your session times out, you'll need to run this function again
#'   to create a new session.
#'
#' @return This function returns an object of class \code{ungadm_session}.
#'
#' @param username A string. Your UNGA-DM Database API username.
#' @param password A string. Your UNGA-DM Database API password.
#'
#' @examples
#' \dontrun{
#' session <- authenticate(
#'   username = "USERNAME",
#'   password = "PASSWORD"
#' )}
#'
#' @export
authenticate <- function(username, password) {
  cat("Authenticating credentials with the UNGA-DM Database API...\n")
  url <- build_api_url(route = "authenticate")
  body = list(
    username = username,
    password = password
  )
  response <- httr::POST(url, body = body, encode = "json")
  response_content <- rawToChar(response$content)
  if(response$status_code != 200) {
    stop(response_content)
  } else {
    cat("Authentication successful!")
    token <- jsonlite::fromJSON(response_content, flatten = TRUE)$token
  }
  session <- list(
    username = username,
    token = token
  )
  class(session) <- "ungadm_session"
  return(session)
}

#' Check authentication with the UNGA-DM Database API
#'
#' @description This function checks whether you are currently authenticated
#'   with the UNGA-DM Database API. You need to provide an object of class
#'   \code{ungadm_session} created by the function \code{authenticate()}.
#'
#' @return This function prints a message to the console but does not return an
#'   object.
#'
#' @param session An object of class \code{ungadm_session} created by
#'   \code{authenticate()}.
#'
#' @examples
#' \dontrun{
#' session <- authenticate(
#'   username = "USERNAME",
#'   password = "PASSWORD"
#' )
#'
#' check_authentication(session)}
#'
#' @export
check_authentication <- function(session) {
  if(class(session) != "ungadm_session") {
    stop("The aurgument session must be an object of class \"ungadm_session\" generated by authenticate().")
  }
  cat("Checking authentication with the UNGA-DM Database API...\n")
  url <- build_api_url(route = "check-authentication")
  response <- httr::GET(
    url,
    httr::add_headers(authorization = session$token),
    encode = "json"
  )
  if(response$status_code != 200) {
    stop(rawToChar(response$content))
  } else {
    cat("You are currently authenticated.")
  }
}
